/* sin_table_generator.c
 * by Richard Cavell
 * June 2025
 *
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>

void fprintf_error()
{
	fprintf(stderr, "%s%i%c", "Couldn't print to output file. Error number : ", errno, '\n');
	exit(EXIT_FAILURE);
}

int main(int argc, char *argv[])
{
	FILE *fp = NULL;
	int ret = 0;

	if (argc != 2)
	{
		fprintf(stderr, "%s%s%s", "Usage: ", argv[0], " outputfile\n");
		exit(EXIT_FAILURE);
	}

	fp = fopen(argv[1], "w");

	ret = fprintf(fp, "%s",
            "* This file was automatically generated by sin_table_generator.c\n"
	    "* by Richard Cavell\n"
	    "* https://github.com/richardcavell\n"
	    "\n");

	if (ret < 0)
		fprintf_error();

	for (i = 0; i < 256; ++i)
	{
		float angle = (float) i / 256.0 * 2 * pi;
		float f = sin(angle) * 256;
		long int j = 0;

		if (f >= 0) j = f;	/* If positive, then simply assign the value */
		else
		{
			long int k = -f;	/* Make sure that we round to zero */
			j = -k;
		}

		ret = fprintf(fp, "%s%li%s%i%s", "\tFDB\t", j, "\t; ", i, " degrees\n");

		if (ret < 0)
			fprintf_error();
	}

	if (fp == NULL)
	{
		fprintf(stderr, "%s%s%s%i%c", "Couldn't open output file ", argv[1], ". Error number : ", errno, '\n');
		exit(EXIT_FAILURE);
	}

	ret = fclose(fp);

	if (ret)
	{
		fprintf(stderr, "%s%s%s%i%c", "Couldn't close output file ", argv[1], ". Error number : ", errno, '\n');
		exit(EXIT_FAILURE);
	}

	return 0;
}

